In [4]:
import pandas as pd
df = pd.read_csv("C:\\Users\\patel\\Downloads\\ecommerce_sales_data\\ecommerce_sales_data.csv")

In [ ]:
%pip install pandas

In [ ]:
df.head(5)

,Order ID,Product Name,Category,Price,Quantity,Total Sales,Customer ID,Customer Age,Customer Gender,Purchase Date,Purchase Time
0,261e3740-c0e9-42b1-bf87-881ac950fa3a,audience,Home & Garden,766.85,4,3067.40,81af1248-afff-46ee-a091-81cf33d0d957,39,Male,25-05-2024,06:28:14
1,0b332b34-46dc-4eaf-a808-fec7e97ffbc6,such,Clothing,331.42,4,1325.68,f3f3f4ac-7ad0-4362-9134-383096d16ac8,21,Male,04-05-2024,19:37:36
2,432e0b36-724d-4521-85ae-f66db8af8105,read,Clothing,708.10,10,7081.00,c4fc4269-3c1d-4b6b-ad23-d437c328d63f,27,Female,07-05-2024,17:54:42
3,ca20fb08-5c65-43b8-9577-3fa49913f93b,skill,Electronics,774.09,2,1548.18,578e2d1a-d92a-449d-8eeb-b704110b2975,51,Female,23-05-2024,22:31:43
4,1dce189c-8c60-455f-a6f2-69bb2cb71539,cold,Electronics,397.22,6,397.22,dc6ed196-0874-46bd-bbb9-c5534f619349,45,Female,15-03-2024,03:08:25

In [ ]:
df.shape

(100172, 11)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100172 entries, 0 to 100171
Data columns (total 11 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Order ID         100172 non-null  object
 1   Product Name     100172 non-null  object
 2   Category         100172 non-null  object
 3   Price            100172 non-null  float64
 4   Quantity         100172 non-null  int64
 5   Total Sales      100172 non-null  float64
 6   Customer ID      100172 non-null  object
 7   Customer Age     100172 non-null  int64
 8   Customer Gender  100172 non-null  object
 9   Purchase Date    100172 non-null  object
 10  Purchase Time    100172 non-null  object
dtypes: float64(2), int64(2), object(7)
memory usage: 8.4+ MB

In [ ]:
df.duplicated().sum()

np.int64(93)

In [ ]:
df.tail()

,Order ID,Product Name,Category,Price,Quantity,Total Sales,Customer ID,Customer Age,Customer Gender,Purchase Date,Purchase Time
100167,6d7e8f9a-0b1c-2345-tuvw-56789012345r,tablet,Electronics,299.00,3,897.00,44r5s6t7-u8v9-0123-4567-89abcdef0123,48,Male,17-09-2024,08:25:44
100168,7e8f9a0b-1c2d-3456-uvwx-67890123456s,style,Clothing,34.20,6,205.20,33s4t5u6-v7w8-1234-5678-9abcdef01234,35,Female,26-06-2024,19:55:11
100169,8f9a0b1c-2d3e-4567-vwxy-78901234567t,building,Toys,67.50,4,270.00,22t3u4v5-w6x7-2345-6789-abcdef012345,60,Male,15-04-2024,15:30:38
100170,9a0b1c2d-3e4f-5678-wxyz-89012345678u,decor,Home & Garden,98.30,2,196.60,11u2v3w4-x5y6-3456-7890-abcdef012345,42,Female,29-10-2024,04:10:12
100171,0b1c2d3e-4f5a-6789-xyza-90123456789v,poem,Books,10.25,9,92.25,00v1w2x3-y4z5-4567-8901-23456789abcd,56,Male,12-12-2024,17:45:55

In [ ]:
df = df.drop_duplicates()

In [ ]:
df.isnull().sum()

Order ID           0
Product Name       0
Category           0
Price              0
Quantity           0
Total Sales        0
Customer ID        0
Customer Age       0
Customer Gender    0
Purchase Date      0
Purchase Time      0
dtype: int64

In [ ]:
df.columns = [
    col.strip().replace(" ","_")
    for col in df.columns
]

In [ ]:
df.columns

Index(['Order_ID', 'Product_Name', 'Category', 'Price', 'Quantity',
       'Total_Sales', 'Customer_ID', 'Customer_Age', 'Customer_Gender',
       'Purchase_Date', 'Purchase_Time'],
      dtype='object')

In [ ]:
df["Purchase_Date"].dtype

dtype('O')

In [ ]:
df["Order_ID"] = [
    f"OrderID{i}" for i in range(1, len(df) + 1)
]

In [ ]:
df["Purchase_Date"] = pd.to_datetime(df["Purchase_Date"])

C:\Users\patel\AppData\Local\Temp\ipykernel_11696\3116118304.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["Purchase_Date"] = pd.to_datetime(df["Purchase_Date"])

In [ ]:
df["Purchase_Date"].dtype

dtype('<M8[ns]')

In [ ]:
df["Purchase_Time"] = pd.to_datetime(df["Purchase_Time"],format="%H:%M:%S").dt.time

In [ ]:
df["Age_Group"] = pd.cut(
    df["Customer_Age"],
    bins=[0, 18, 30, 45, 60, 100],
    labels=[
        "Under 18",
        "18-30",
        "31-45",
        "46-60",
        "60+"
    ]
)

In [ ]:
df["Year"] = df["Purchase_Date"].dt.year

df["Month"] = df["Purchase_Date"].dt.month

df["Month_Name"] = df["Purchase_Date"].dt.month_name()

df["Quarter"] = df["Purchase_Date"].dt.quarter

df["Day_Name"] = df["Purchase_Date"].dt.day_name()

In [ ]:
df["Hour"] = pd.to_datetime(
    df["Purchase_Time"],
    format="%H:%M:%S"
).dt.hour

In [ ]:
df.head()

,Order_ID,Product_Name,Category,Price,Quantity,Total_Sales,Customer_ID,Customer_Age,Customer_Gender,Purchase_Date,Purchase_Time,Age_Group,Year,Month,Month_Name,Quarter,Day_Name,Hour
0,OrderID1,audience,Home & Garden,766.85,4,3067.40,81af1248-afff-46ee-a091-81cf33d0d957,39,Male,2024-05-25,06:28:14,31-45,2024,5,May,2,Saturday,6
1,OrderID2,such,Clothing,331.42,4,1325.68,f3f3f4ac-7ad0-4362-9134-383096d16ac8,21,Male,2024-05-04,19:37:36,18-30,2024,5,May,2,Saturday,19
2,OrderID3,read,Clothing,708.10,10,7081.00,c4fc4269-3c1d-4b6b-ad23-d437c328d63f,27,Female,2024-05-07,17:54:42,18-30,2024,5,May,2,Tuesday,17
3,OrderID4,skill,Electronics,774.09,2,1548.18,578e2d1a-d92a-449d-8eeb-b704110b2975,51,Female,2024-05-23,22:31:43,46-60,2024,5,May,2,Thursday,22
4,OrderID5,cold,Electronics,397.22,6,397.22,dc6ed196-0874-46bd-bbb9-c5534f619349,45,Female,2024-03-15,03:08:25,31-45,2024,3,March,1,Friday,3

In [ ]:
dim_product = df[
    [
        "Product_Name",
        "Category",
        "Price"
    ]
].drop_duplicates()

In [ ]:
dim_product["Product_ID"] = range(
    1,
    len(dim_product) + 1
)

In [ ]:
dim_customer = df[
    [
        "Customer_ID",
        "Customer_Age",
        "Customer_Gender",
        "Age_Group"
    ]
].drop_duplicates()

In [ ]:
dim_date = pd.DataFrame({
    "Date": df["Purchase_Date"].drop_duplicates()
})

dim_date["Year"] = dim_date["Date"].dt.year

dim_date["Month"] = dim_date["Date"].dt.month

dim_date["Month_Name"] = (
    dim_date["Date"].dt.month_name()
)

dim_date["Quarter"] = (
    "Q" + dim_date["Date"].dt.quarter.astype(str)
)

dim_date["Day"] = dim_date["Date"].dt.day

dim_date["Day Name"] = (
    dim_date["Date"].dt.day_name()
)

In [ ]:
product_lookup = dim_product[
    ["Product_ID", "Product_Name", "Category", "Price"]
].copy()
df = df.merge(
    product_lookup,
    on=["Product_Name", "Category", "Price"],
    how="left"
)
df["Product_ID"].isna().sum()

np.int64(0)

In [ ]:
df.to_csv("Ecommerce_sales_fact.csv", index=False)

In [ ]:
dim_product.to_csv("Ecommerce_sales_products.csv")

In [ ]:
dim_date.to_csv("Ecommerce_sales_time.csv")

In [ ]:
dim_customer.to_csv("Ecommerce_sales_Customer.csv")

In [ ]:
from sqlalchemy import create_engine

username = "postgres"
password = "618661"
host = "localhost"
port = "5432"
database = "ecommerce_analytics"

engine = create_engine(
    f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}"
)

print("PostgreSQL connection created")

PostgreSQL connection created

In [ ]:
print("dim_product :", dim_product.shape)
print("dim_customer:", dim_customer.shape)
print("dim_date    :", dim_date.shape)
print("fact_sales  :", df.shape)

dim_product : (100062, 4)
dim_customer: (100074, 4)
dim_date    : (185, 7)
fact_sales  : (100079, 19)

In [ ]:
print(dim_product.columns.tolist())
print(dim_customer.columns.tolist())
print(dim_date.columns.tolist())
print(df.columns.tolist())

['Product_Name', 'Category', 'Price', 'Product_ID']
['Customer_ID', 'Customer_Age', 'Customer_Gender', 'Age_Group']
['Date', 'Year', 'Month', 'Month_Name', 'Quarter', 'Day', 'Day Name']
['Order_ID', 'Product_Name', 'Category', 'Price', 'Quantity', 'Total_Sales', 'Customer_ID', 'Customer_Age', 'Customer_Gender', 'Purchase_Date', 'Purchase_Time', 'Age_Group', 'Year', 'Month', 'Month_Name', 'Quarter', 'Day_Name', 'Hour', 'Product_ID']

In [ ]:
dim_product.to_sql(
    "dim_product",
    engine,
    if_exists="replace",
    index=False
)

dim_customer.to_sql(
    "dim_customer",
    engine,
    if_exists="replace",
    index=False
)

dim_date.to_sql(
    "dim_date",
    engine,
    if_exists="replace",
    index=False
)

df.to_sql(
    "fact_sales",
    engine,
    if_exists="replace",
    index=False
)

print("All 4 tables uploaded successfully!")

All 4 tables uploaded successfully!

In [ ]:
# new dataset file load if new data add
# like example  =  new dataset = pd.read_csv("file location")
# file name .to_sql(
#     "fact_sales",
#     engine,
#     if_exists="append",
#     index=False
# )

In [ ]:
# append = pd.read_csv("path to new dataset file.csv")

# # Remove unwanted index column
# append = append.drop(columns=["Unnamed: 0"], errors="ignore")

# # Upload to PostgreSQL
# append.to_sql(
#     "dim_date",
#     engine,
#     if_exists="append",
#     index=False
# )

# print("New date data added successfully!")